### ISSUE TITLE
将布局grid的某一列的元素全部移动到其他列或全部删除后就无法再将元素移动到那一列了

### ISSUE THREAD

**Issue by dearshor** [henryyan/jquery-ui-portlet#1]
# 问题描述

如果将布局grid的某一列的元素全部移动到其他列或全部删除，就无法再将元素移动到那一列了。
# 测试环境

chrome 版本 23.0.1271.64 m
firefox 16.0.2
IE 9.0.8112
OS: windows 7 ultimate x86-32
# 其他

通过 file:// 协议访问时，在chrome里ajax内容显示不出来，看了一下console log，发现是出于安全原因，一些操作被chrome禁止了：Origin null is not allowed by Access-Control-Allow-Origin.

**Comment by henryyan** [comment]
已经修复
