### ISSUE TITLE
Add Column after initialization possible ?

### ISSUE THREAD

**Issue by mafar** [henryyan/jquery-ui-portlet#14]
Same as `$('#portlet-demo').portlet('toggle', 'shopping');` is it possible to add another column after a portlet has been initialized ? 

I mean lets`s say portlet() started with one column and then user wanted to add another column later ?

**Comment by henryyan** [comment]
yap, the feature has supported, demo: [http://www.kafeitu.me/demo/jquery-ui-portlet/demo/dynamic-add.html](http://www.kafeitu.me/demo/jquery-ui-portlet/demo/dynamic-add.html), click button "动态添加News".
I'll translate to english laster!
